# -*- coding: utf-8 -*-
"""hugging_face.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XM08kZZlDjzq-f159IDHWV3Rmd6KmOJ9
"""

#!pip install gradio

#!pip install huggingface_hub

from huggingface_hub import whoami
from google.colab import userdata

# Get your Hugging Face token from Colab Secrets
hf_token = userdata.get('HF_TOKEN')

# Verify the token by checking your identity
try:
    user_info = whoami(token=hf_token)
    print(f"Logged in as: {user_info['name']}")
except Exception as e:
    print(f"Could not log in: {e}")
    print("Please make sure you have added your Hugging Face token to Colab Secrets with the name 'HF_TOKEN'")

import gradio as gr
import tempfile

import torch

from transformers import AutoTokenizer, AutoModelForSeq2SeqLM

MODEL_NAME = "facebook/bart-large-cnn"

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_NAME,
    token=hf_token
)

model = AutoModelForSeq2SeqLM.from_pretrained(
    MODEL_NAME,
    token=hf_token,
    dtype=torch.float16 if torch.cuda.is_available() else torch.float32
)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)

# Summarization function
def summarize_text(text, max_length, min_length):
    if not text.strip():
        return "Please enter some text."

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=1024
    ).to(device)

    summary_ids = model.generate(
        **inputs,
        max_length=max_length,
        min_length=min_length,
        num_beams=4,
        length_penalty=2.0,
        early_stopping=True
    )

    return tokenizer.decode(summary_ids[0], skip_special_tokens=True)

# Export functionality
def export_summary(summary_text):
    temp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".txt")
    with open(temp_file.name, "w", encoding="utf-8") as f:
        f.write(summary_text)
    return temp_file.name

# Gradio Interface
with gr.Blocks(theme=gr.themes.Soft()) as app:

    gr.Markdown(" Hugging Face Text Summarizer")

    input_text = gr.Textbox(
        label="Input Text",
        lines=10,
        placeholder="Paste text here..."
    )

    with gr.Row():
        max_len = gr.Slider(50, 300, value=150, label="Max Summary Length")
        min_len = gr.Slider(20, 150, value=50, label="Min Summary Length")

    summarize_btn = gr.Button("Summarize")

    output_text = gr.Textbox(
        label="Summary",
        lines=6
    )

    export_btn = gr.Button("Export Summary")
    file_output = gr.File(label="Download")

    summarize_btn.click(
        fn=summarize_text,
        inputs=[input_text, max_len, min_len],
        outputs=output_text
    )

    export_btn.click(
        fn=export_summary,
        inputs=output_text,
        outputs=file_output
    )

app.launch(debug=True)